### ISSUE TITLE
CorrosionConfig.cmake when used as a subdirectory

### ISSUE THREAD

**Issue by ratmice** [corrosion-rs/corrosion#141]
I'm overall pretty new to cmake, having not really used it before.
If I have a top-level CMakeLists.txt which is from another project, and knows nothing about corrosion

```
add_subdirectory(corrosion)
# foo/CMakeLists calls find_package(Corrosion REQUIRED)
add_subdirectory(foo)
```

This ends up with an error on the `foo/CMakeLists.txt find_package` line:
```
  By not providing "FindCorrosion.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Corrosion", but CMake did not find one.

  Could not find a package configuration file provided by "Corrosion" with
  any of the following names:

    CorrosionConfig.cmake
```

It appears `CorrosionConfig.cmake` never gets generated from `CorrosionConfig.cmake.in`
unless I remove the following from Corrosion/CMakeLists.txt
```
# If Corrosion is a subdirectory, do not enable its install code
if (NOT _CORROSION_TOP_LEVEL)
    return()
endif()
```

After changing that it generates `CorrosionConfig.cmake`, but it seems like 

* The `list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/cmake)` doesn't make it to `foo/CMakeLists.txt`
* The place where `CorrosionConfig.cmake` is in the build tree isn't added to `CMAKE_MODULE_PATH` so it still can't find it.

It seems like I may have to go with the pre-installed corrosion, but it seemed like this was something that corrosion is trying to make work.
Edit: I should note this comment https://github.com/corrosion-rs/corrosion/blob/master/CMakeLists.txt#L141
which is *after* currently after the call to `return()` so doesn't appear to run.

**Comment by jschwe** [comment]
I personally don't use corrosion as a subdirectory, so I have little experience here, but:

- I think find_package is only expected to work if you have the package installed.  CorrosionConfig.cmake should not be necessary.
- The documentation recommends simply using `add_subdirectory` without `find_package`. However, since `add_subdirectory` opens a new scope, this means that variables exposes by `FindRust` (such as `Rust_VERSION`) will not be available to you in this case.
- Since functions are global in scope, you can still access all corrosion functions.

**Comment by ratmice** [comment]
Alright, If it isn't a supported setup, it's probably best to close this.

I did finally manage to get the installed corrosion to work with the tree, because the top-level tree doesn't search installed packages, I had to find_package like so:
`find_package(Corrosion REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)`
