### ISSUE TITLE
usage of .cargo/config

### ISSUE THREAD

**Issue by ratmice** [corrosion-rs/corrosion#150]
I was looking to see if it was possible to use a .cargo/config.toml (in my source directory),
I didn't find a way to do so, this line in [FindRust.cmake](https://github.com/corrosion-rs/corrosion/blob/master/cmake/FindRust.cmake#L347-L353) generates a `.cargo/config` in the build directory which is used instead.

This sets the `target-dir` and optionally `rustcflags` fields.
I was midly curious if it would be possible to move this to use the `--target-dir` arg, or `CARGO_TARGET_DIR` or `CARGO_BUILD_TARGET_DIR` env vars instead.

This made me curious what the order of lookups for this setting is, and it appears to be the order in which I have listed them,
i.e. `--target-dir` will take precedence, and all the above will override `.cargo/config`.

as such, the following will fail, 
```
cmake -GNinja ..
CARGO_TARGET_DIR="foo" ninja
```

when "cargo/build" eventually makes it's way to `build_byproducts` in https://github.com/corrosion-rs/corrosion/blob/master/cmake/Corrosion.cmake#L299

as far as I could see, that was the only place its relied upon though.

**Comment by jschwe** [comment]
> I was looking to see if it was possible to use a .cargo/config.toml (in my source directory),
> I didn't find a way to do so, this line in [FindRust.cmake](https://github.com/corrosion-rs/corrosion/blob/master/cmake/FindRust.cmake#L347-L353) generates a .cargo/config in the build directory which is used instead.

I theory you should be able to use a config file, you would just have to place it in a parent directory of the build directory. Contents of [config.toml](https://doc.rust-lang.org/cargo/reference/config.html) are merged by cargo where possible. 
I do vaguely remember us having some issues related to the config.toml in  a project at work, but I don't remember any specifics.

In the long run I would personally like to get rid of generating this `config` file and just pass the rustflags and target-dir to cargo directly.

> ```
> cmake -GNinja ..
> CARGO_TARGET_DIR="foo" ninja
> ```

I don't think we can support this, since AFAIK the output directory needs to be known at configure time, while this approach sets the `CARGO_TARGET_DIR` at generate time.

**Comment by ratmice** [comment]
I'll have to try that, I'm not certain it'll work very well, since in particular i'm kind of trying to generate config.toml *from* cmake.
So it'd be much cleaner if I could just generate in build dir.

and totally agree about not being able to support `CARGO_TARGET_DIR`, I just mentioned it not to ask that we support it.
But to say that irrespective of being able to generate `config` in build directory, `config` usage already causes issues, since it isn't reliable.

**Comment by jschwe** [comment]
If that doesn't work out, feel free to have a look at removing the `.cargo/config` and passing the rustflags directly. We do already support setting rustflags (see `corrosion_add_target_rustflags`), you would just have to add the flags to the per target properties. This should be pretty straightforward unless the Rustflags contain something that needs to be escaped.

Adding the target-dir parameter to cargo-build should also be pretty straight forward.

**Comment by Be-ing** [comment]
I'm working on a [code generator](https://github.com/KDAB/cxx-qt) that generates C++ headers which need to be available in a predictable location for `target_include_directories`. I think the most reasonable way to handle this for build.rs scripts to rely on the CARGO_TARGET_DIR environment variable. The design of Cargo makes this annoyingly difficult by not setting CARGO_TARGET_DIR for build.rs scripts because build.rs scripts should generally use OUT_DIR instead. Apparently setting `target-dir` via a config file doesn't set CARGO_TARGET_DIR for build.rs either. However, build.rs scripts can access CARGO_TARGET_DIR if something else sets the environment variable when invoking cargo. So for my use case, I think it would be best to replace `.cargo/config` with setting the CARGO_TARGET_DIR environment variable when calling `cargo build`.

**Comment by jschwe** [comment]
> I'm working on a [code generator](https://github.com/KDAB/cxx-qt) that generates C++ headers which need to be available in a predictable location for target_include_directories.

You could also generate files to some location like `${CMAKE_BINARY_DIR}/generated/xyz` and then use `corrosion_set_env_vars()` to pass the location via an environment variable to your build script. Is there a specific reason why you want to generate to `CARGO_TARGET_DIR`?

**Comment by Be-ing** [comment]
On further thought, I am going with that approach instead of assuming my use of CARGO_TARGET_DIR doesn't clash with implementation details of cargo.

**Comment by Be-ing** [comment]
I [implemented that approach](https://github.com/KDAB/cxx-qt/pull/218) of explicitly telling the code generator where to output the headers by setting an environment variable and it works well. I have written a [proposal](https://github.com/dtolnay/cxx/issues/462#issuecomment-1229262546) for upstreaming this approach into cxx-builder. That would allow Corrosion to automatically set that environment variable so using cxx with CMake wouldn't require anything different than using Corrosion with any other Rust library. @jschwe I would appreciate your input on that proposal.

**Comment by ratmice** [comment]
FWIW, I haven't had a chance to work on my corrosion using projects in a while, but I believe that the recent commit in https://github.com/corrosion-rs/corrosion/pull/165/files/1a605d49384a3d7e5de9d756ae9aef824cab5ba4 looks like it should be sufficient for what I needed.
