### ISSUE TITLE
Add sources to project for IDE integration

### ISSUE THREAD

**Issue by MarkKMueller** [corrosion-rs/corrosion#173]
I just started using corrosion and my IDE of choice is qtcreator. The build works fine with corrosion, but is there a way to use corrosion to add the source files to my cmake project such that the IDE can get them from the project and manipulate them like a C or other source file?

**Comment by hunger** [comment]
So you would like to see the rust sources built by corrosion in Qt Creator?

I am not aware of any dynamic way to discover files at build time in cmake. CMake will also not run arbitrary commands at configure time, so we can not make corrosion deicover files at configure time. This is why I doubt we can make corrosion tell cmake about all the files it builds with cargo -- so that cmake can then tell Creator about those files in turn.

As a work-around you should be able to add a target into your own CMakeLists.txt file, which you then tell cmake not to build. IIRC Creator will include those files anyway. They probably will be grey-ed out, but they should still be accessible via Ctrl-K and such.

**Comment by hunger** [comment]
Actually corrosion *does* run a custom command during configure time and we could hook into that and generate a target. Unfortunately `cargo metadata` does is not that helpful: It only lists the main source file for each target. That is enough for rust to build things, butcreator would need all the files directly and indirectly pulled in.

**Comment by MarkKMueller** [comment]
I've created a topic for [this](https://forum.qt.io/topic/136101/qt-creator-rust-development-with-corrosion) on the Qt Tools forum.

**Comment by jschwe** [comment]
There seem to be 2 main aspects to this issue.

1. Discovering which source files belong to a crate. According to this [rust-internals thread](https://internals.rust-lang.org/t/getting-all-sources-for-a-particular-target/9678), you would need  to actually build the target to be able to list all the source files. For most projects simply finding all `.rs` files under `src` (and subdirectories) may be sufficient, but I'm not sure if I like this approach.
2. Adding the source files to the library properties: Corrosion exposes the library as an `INTERFACE` library. Since CMake 3.19 it is possible to add source files to an `INTERFACE` library (see [docs](https://cmake.org/cmake/help/latest/command/add_library.html#interface-libraries) ). Maybe you could try first if manually adding some files of your project as source files (via [target_sources](https://cmake.org/cmake/help/latest/command/target_sources.html) ) to your rust library makes it work as expected with QtCreator.
