### ISSUE TITLE
Add parameter to corrosion_import_crate to return list of added targets.

### ISSUE THREAD

**Issue by jschwe** [corrosion-rs/corrosion#218]
This could be used by the caller to set some properties for all (or a filtered subset) of targets.
You can already manually set the properties, but in cases where there are a lot of targets, it may be more convenient to just iterate over a list that corrosion provides.

**Comment by temeddix** [comment]
Yeah, this is definitely needed in actual developement.

**Comment by jschwe** [comment]
>  this is definitely needed in actual developement.

I'm curious what your usecase is that you "definitely need" this. From my point of view it's just a minor convenience improvement. Could you elaborate?

**Comment by temeddix** [comment]
We have a situation where we have to compile multiple crates inside a workspace crate. Since our repository is public, it is https://github.com/cunarist/app-template. It's a template for app development written in Fltuter and Rust

We have a workspace rust crate `native` and some other library crates insied it, like this:
- `native`: workspace crate
  -  `first_crate`: library crate
  - `second_crate`: library crate
  - ...(More library crates will be added in the future)

With this situation, we can compile multiple library crates at once with a CMAKE file like this:
```cmake
# Part of CMAKE file
corrosion_import_crate(MANIFEST_PATH ../native/Cargo.toml)
set(CRATE_NAME "first_crate")
target_link_libraries(${BINARY_NAME} PRIVATE ${CRATE_NAME})
list(APPEND PLUGIN_BUNDLED_LIBRARIES $<TARGET_FILE:${CRATE_NAME}-shared>)
set(CRATE_NAME "second_crate")
target_link_libraries(${BINARY_NAME} PRIVATE ${CRATE_NAME})
list(APPEND PLUGIN_BUNDLED_LIBRARIES $<TARGET_FILE:${CRATE_NAME}-shared>)
```
However, if we add new library crate insied the `native` workspace crate, we have to modify this file again and again. Therefore it would be nice to have something like this:
```cmake
# Part of CMAKE file
corrosion_import_crate(MANIFEST_PATH ../native/Cargo.toml)
foreach(LIB ${LIBS}) # Assuming that a list name LIBS is from corrosion_import_crate
if (TARGET ${LIB})
    list(FIND VISITED_TARGETS ${LIB} VISITED)
    if (${VISITED} EQUAL -1)
        get_target_property(LIB_FILE ${LIB} LOCATION)
        get_link_libraries(LINK_LIB_FILES ${LIB})
        list(APPEND LIB_FILES ${LIB_FILE} ${LINK_LIB_FILES})
    endif()
endif()
endforeach()
```

**Comment by jschwe** [comment]
I'm currently a bit tight on time, but if you would be interested in opening a PR, this feature would be quite simple to implement.

We already save the information here in [`created_targets`](https://github.com/corrosion-rs/corrosion/blob/e3d8d200082fd49350dc6b9c4f974efc2402f6ae/cmake/CorrosionGenerator.cmake#L203), so all that has to be done is propogate this variable back up the callchain to `corrosion_import_crate` and add a parameter to `corrosion_import_crate` for the user to specify a variable name, so `corrosion_import_crate` can use `set(${var_name} "${imported_crates} PARENT_SCOPE)` to propogate this back to the user.

**Comment by jschwe** [comment]
Actually things happened, and this issue has moved up on my priority list. I'll probably be able to work on this at the end of the week.

**Comment by temeddix** [comment]
I did make a pull request as you described. Please tell me if there is any problem.

**Comment by jschwe** [comment]
>  P.S: I didn't see that you mentioned about your priority😗. Well, I already made a PR request anyway...

I didn't have the time yet, so definitely thanks for doing this! Closing, since #312 is merged now.
