### ISSUE TITLE
Problem with arm/thumb v8 

### ISSUE THREAD

**Issue by mean00** [corrosion-rs/corrosion#226]
Hi
First, thank you for Corrosion!

The arm/thumb triplet for arm/thumb v8 is a bit special. The available rust toolchains are : 
thumbv8m.base-none-eabi 
thumbv8m.main-none-eabi
thumbv8m.main-none-eabihf

From what i gathered, the dot after v8m is confusing corrosion as it thinks this is a file to load and an internal test fails as it does not end with .json.

The easy workaround is just to remove the test in corrosion.
I don't know how to fix that in a better way, apart from changing the test to check if the target explicitly ends with ".json".

Thank you

PS: This arch is used by Cortex M23 and Cortex M33 MCUs

**Comment by jschwe** [comment]
Thanks for the report!

> The easy workaround is just to remove the test in corrosion.

The failing test actually does not prevent you from using corrosion, as the tests should only run when building / installing corrosion itself. Unless your host system is `thumbv8m` this should not be a problem, since you would be building corrosion for the host system (If you are using CMake >= 3.19 you even do not need to build/install corrosion at all and can just use it as a submodule). 

When building your own project with corrosion for ` thumbv8` you should only get a warning, which you can surpress by setting `CORROSION_NO_WARN_PARSE_TARGET_TRIPLE_FAILED`  beforehand. The target triple detection is used by corrosion to determine which libraries need to be linked in (required by ` std`), but for your target this should not be relevant.

I'll keep this issue open so that I can fix the test at some point.

**Comment by mean00** [comment]
I'm using the subdir option as far as corrosion is concerned ( i.e. add_subdirectory(blah blah/corrosion) to the main project)
to minimize the dependencies on the host system, so it seems the test failing is stopping the build.

Maybe i missed something ?

(And indeed i also had to set CORROSION_NO_WARN_PARSE_TARGET_TRIPLE_FAILED)

Thank you

**Comment by jschwe** [comment]
Ah sorry, it actually does fail currently when a `.` is encountered. I'll push a fix.
