### ISSUE TITLE
Windows: ` $<TARGET_FILE:libtarget-shared>` refers to non-existent file when `CMAKE_LIBRARY_OUTPUT_DIRECTORY` is set

### ISSUE THREAD

**Issue by tronical** [corrosion-rs/corrosion#321]
When `CMAKE_LIBRARY_OUTPUT_DIRECTORY` is set, the `TARGET_FILE` generator expression for an imported cdylib library crate points to a non-existent file. This makes it difficult to provide an "install" target that installs generated DLLs.

See the attached zip archive for a reproducer.

Built on Windows with CMake 3.24.2, Ninja, and MSVC:

```
>cmake -DCMAKE_INSTALL_PREFIX=c:\dev\corrosion-bug -GNinja ..
-- The CXX compiler identification is MSVC 19.34.31937.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Rust Toolchain: stable-x86_64-pc-windows-msvc
-- Rust Target: x86_64-pc-windows-msvc
-- Found Rust: C:/Users/Simon Hausmann/.rustup/toolchains/stable-x86_64-pc-windows-msvc/bin/rustc.exe (found version "1.66.1")
-- Using Corrosion as a subdirectory
-- Configuring done
-- Generating done
-- Build files have been written to: C:/dev/corrosion-bug/build

>cmake --build .
...

>cmake --install .
-- Install configuration: "Debug"
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot find "C:/dev/corrosion-bug/build/corrosion_bug.dll":
  File exists.

```

[corrosion-bug-main.zip](https://github.com/corrosion-rs/corrosion/files/10756813/corrosion-bug-main.zip)

(The reproducer is also at https://github.com/tronical/corrosion-bug but I might delete that repo in the future, so archiving as zip here to be on the safe side :)

**Comment by tronical** [comment]
Is this perhaps a bug in the way that we're trying to install the artefacts? I'd be happy with a workaround, if this is not fixable due to the way deferred calls are made to apply the output directory settings.

**Comment by jschwe** [comment]
I won't have time to look into this before the weekend, but just as some food for thoughts from my phone:

I _think_ that the location property is supposed to be set and read from the interface library i.e. without the static/shared suffix, since that is the target name we officially expose to the user. I'm not sure if we modify the location property also on the actual internal target, but maybe we should do that too if we aren't already.

Probably things also go wrong in the regex [here](https://github.com/corrosion-rs/corrosion/blob/master/cmake/Corrosion.cmake#L131), since the crate name contains an `-`:

```cmake
    if("${target_name}" MATCHES "^([^-]+)-(static|shared)$")
```

In my opinion the deferred calls should not play a role at all, since the genex is evaluated at build time, while the deferred calls are still at configure time.

**Comment by tronical** [comment]
Thank you for the hint! Now I know where you dig. I’ll poke the code tomorrow.

**Comment by jschwe** [comment]
I also have a vague memory (but maybe I'm misremembering) that potentially I encountered issues with the TARGET_FILE genex not evaluating as expected, but manually reading the location property working.

**Comment by tronical** [comment]
You are right, this is an issue with the regex. I'll submit a PR.
