### ISSUE TITLE
[Enhancement]: Vcpkg support

### ISSUE THREAD

**Issue by bconn98** [corrosion-rs/corrosion#482]
### Current Behavior

Corrosion supports installation via submodule or `FetchContent`.

### Expected Behavior

`Vcpkg` by default disables `FetchContent`, while it can be forced to allow it to work, it would be beneficial to provide a port for installing via Vcpkg. The added support is minimal as you already provide installation rules. It is 2 files that are added to the Microsoft vcpkg repo with small updates following a new release.

### Environment

```markdown
- OS:
- CMake:
- CMake Generator:
```

**Comment by jschwe** [comment]
I'm not familiar with `vcpkg` and currently don't have much free capacity. Corrosion is also available [via homebrew](https://formulae.brew.sh/formula/corrosion), which is maintained by the community and not by me or any of the other maintainers directly. If someone contributed vcpkg support, I would gladly add it to corrosions documentation.

**Comment by bconn98** [comment]
Cool, I can throw it together at some point this week. Do you know when the cmake install rules for the tool were added? I can add backwards compatibility support through that point. I know my use case is on v0.4.5 but I can take it back farther.

**Comment by jschwe** [comment]
The install rules have been there from the beginning - at the very least starting from Corrosion 0.2.
It probably doesn't make much sense to add anything before v0.4 though, since I think v0.3 and before will not work properly on windows with the most recent Rust versions.  Corrosion also follows semver, so I'm not sure sure if there is much value adding v0.4 versions before the latest version (v0.4.7) since there shouldn't be any breaking changes.

**Comment by jschwe** [comment]
The upstream [`vcpkg` PR](https://github.com/microsoft/vcpkg/pull/36369#issuecomment-1966055372) has apparently been rejected, so I'll be closing this issue.
Just to be clear, from my side I don't object adding corrosion to vcpkg, but I don't see any point in keeping this issue when upstream has rejected the proposal.

**Comment by bconn98** [comment]
Agreed, the PR we applied a few weeks ago covers ensures compatibility with Vcpkg so I should be all set.
