### ISSUE TITLE
Eliminate the build-script crate

### ISSUE THREAD

**Issue by AndrewGaspar** [corrosion-rs/corrosion#54]
It seems like we don't actually need the build-script crate - everything we need should be doable with CARGO_TARGET_<triple>_RUSTFLAGS.

**Comment by jschwe** [comment]
Just to make the description more precise, this refers to the `corrosion-build` crate under `integrator`.

Probably this should not be done via `CARGO_TARGET_<target>_RUSTFLAGS, since `RUSTFLAGS also would apply to dependencies. Instead it might be preferable to invoke `cargo rustc` - but maybe that is something we should do in general for target specific `RUSTFLAGS`
